### PR TITLE
I made the game better and accidentally updated SDK to 4.1 (pelase accept)

### PR DESCRIPTION
**Pull request by 5w14**
I've made the UI better. 

Переходи на юнити, кринж!

### CODE REVIEW

**Comment by 5w14** [comment]
i've added contributors (me)

**Comment by 5w14** [comment]
added mental supporters

**Comment by 5w14** [comment]
crazy 
i was crazy once 
they locked me in a room
a rubber room
a rubber room with rats
and rats make me go crazy

**Comment by CaptainSqrBeard** [comment]
looks like you never worked with godot before :trollface:

**Pull request closed without merging**
